# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7fdfb59b91cfe32e274d5250c49d716cd44194b3a79713f4f448c8630a411487593a600b1a111ea59132ea7513ad16fdd774003a4a57b4e4bb99ce8b8e34749

test:
  secret_key_base: bde0d1adbe0369c1049714a1d2836eec441e21658cb86ac9cc0d9145bd8bb90cc10ea2c0df3b2b9e1df2adee5c5a5c236500176fee7d1cc80060fba46463e816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
